#ifndef EXCEPTION_H
#define EXCEPTION_H

	enum EXCEPTION { EX_BOARD_ALREADY_LOADED, EX_BOARD_NOT_LOADED, EX_BAD_BOARD_LOAD_ATTEMPT, EX_FAIL_FILE_OPEN, EX_OUT_OF_BOARD_RANGE,
	EX_ILLEGAL_BOARD_OPERATION, EX_HTTP_GET_FAIL};

#endif